static const char black[]       = "#1A1826";
static const char gray2[]       = "#302D41"; // unfocused window border
static const char gray3[]       = "#988BA2";
static const char gray4[]       = "#C3BAC6";
static const char blue[]        = "#96CDFB";  // focused window border
static const char green[]       = "#ABE9B3";
static const char red[]         = "#F28FAD";
static const char orange[]      = "#F8BD96";
static const char yellow[]      = "#FAE3B0";
static const char pink[]        = "#E8A2AF";
static const char col_borderbar[]  = "#1A1826"; // inner border
